### PR TITLE
New meteor integration using meteor/graphql

### PR DESCRIPTION
**Pull request by timbrandin**
Reference package: https://github.com/apollostack/meteor-integration

### CODE REVIEW

**Comment by helfer** [comment]
Wait, I'm confused. Is `meteor/apollo` actually already a thing or are the docs getting ahead of the code here?

**Comment by timbrandin** [comment]
The docs are ahead of the code ;)

**Comment by dburles** [comment]
@timbrandin is from the future 😂

**Comment by lorensr** [comment]
Haha yes, I did DDD (docs-driven development) 😄 

@timbrandin `npm add` -> `npm install` and client api changed: https://github.com/apollostack/meteor-integration#client

Also, you get `context.userId`, not `.user`. Example use: https://github.com/apollostack/meteor-integration#server

**Comment by helfer** [comment]
@lorensr  Is this implemented now? If so, feel free to merge it at your convenience.

**Comment by stubailo** [comment]
@lorensr do you think this is ready to merge?

**Comment by lorensr** [comment]
Sorry, behind on things! Not ready, the API has changed. Might be best to just link to the package readme? 

https://github.com/apollostack/meteor-integration/#usage

Or alternatively, move the usage section to docs.apollostack, and link from the readme to the docs.

**Comment by stubailo** [comment]
Up to you - so far, I've been keeping everything in the docs, but we could do either way. I think duplicating the content isn't ideal.

**Pull request closed without merging**
