### PR TITLE
Include middleware in apollo-client docs

### PR DESCRIPTION
**Pull request by czbaker**
I wrote examples of writing basic middleware for use with createNetworkInterface.  I don't go into detail regarding how it would be used to manipulate headers and such, but that could also be added if needed.

### CODE REVIEW

**Comment by helfer** [comment]
Thanks a lot for starting this! I think it would be great if it gave some real examples of how to use middleware, most commonly probably for adding an auth token or setting a custom header. When you do, make sure to test the code, because people will definitely copy-paste it.

**Comment by stubailo** [comment]
Agreed, at least the code examples should demonstrate modifying the request in some way.

**Comment by czbaker** [comment]
Okay, I could modify the code sample to show that, then.

**Comment by stubailo** [comment]
Yes please! This will be very valuable.

**Comment by czbaker** [comment]
I just added a commit to this PR that shows an example of taking a token from localStorage (JWT, for example) and adding it to the HTTP header of the request being processed.

Hopefully this is a more practical and useful example!

**Comment by helfer** [comment]
Awesome, thanks a lot!

**Comment by sorenbs** [comment]
Does this actually work? I had to change the example to this to make it work:

```
networkInterface.use([{
  applyMiddleware: (req, next) => {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    req.options.headers.authorization = window.localStorage.getItem('token')
      ? `Bearer ${window.localStorage.getItem('token')}` : null;

    next();
  }
}])
```

Specifically:

1. `.use` takes a list
2. `applyMiddleware` is a function on the object
3. it should be `applyMiddleware`, not `applyMiddleWare`
4. it should be `option.headers`, not `option.header`

**Comment by helfer** [comment]
@sorenbs: correct. I think PR #107 fixes this.

**Comment by sorenbs** [comment]
@helfer Thanks!

**Pull request merged**
