### PR TITLE
apolloServer mocks no longer overwrite resolvers

### PR DESCRIPTION
**Pull request by rdrey**
Documentation update for [Allows resolvers to be used with
mocks](https://github.com/apollostack/apollo-server/pull/9) (https://github.com/apollostack/apollo-server/pull/9)

### CODE REVIEW

**Comment by stubailo** [comment]
Hmm, now that I see this, I'm a little sad because I think this makes mocks less useful for people defining their schema with `GraphQL-JS`? I can totally imagine a use case where you have a working GraphQL schema, and you want to replace the resolvers with mocks.

**Comment by rdrey** [comment]
You can simply remove your resolvers from the `apolloServer()` config completely and have a nice fallback to mocks. :) I think mocks still provide a lot of value.

**Comment by stubailo** [comment]
Sure, I just mean for the case where people already are using GraphQL-JS without apollo at all, and just want to add some mocks.

**Comment by helfer** [comment]
They can still add mocks through GraphQL tools. This only applies to apolloServer.

**Comment by stubailo** [comment]
Perfect! I was hoping it was something like that.

**Pull request merged**
