### PR TITLE
Add concrete example of store rehydration using react

### PR DESCRIPTION
**Pull request by bwhitty**
This just gives a more concrete example of how to use store rehydration using React. Also fixes an issue where syntax highlight on this snippet wasn't working because hexo bails when it sees HTML inside a JS snippet.

### CODE REVIEW

**Comment by stubailo** [comment]
Looks great! Perhaps we should re-organize this soon into some separate pages about server-side rendering/hydration.

**Comment by bwhitty** [comment]
Yeah, while SSR is not something (most) everyone needs there's so many different solutions to it that it may warrant a whole section on it. One for React, Angular2, maybe Rails, etc.

**Comment by stubailo** [comment]
Yeah, and I think there's an opportunity to make it really easy! I guess I should stop mixing together hydration and SSR. Is there even a name for store rehydration that sounds nicer?

**Comment by bwhitty** [comment]
I'm not really sure there's a difference... you can just call it "Passing an initial state" because that's what it is. The whole pattern, at least for redux, is covered in a doc section under ["server rendering"](http://redux.js.org/docs/recipes/ServerRendering.html) so there's that.

**Comment by stubailo** [comment]
Yeah I guess server rendering sounds really expensive and hard whereas the hydration can be much easier!

**Pull request merged**
