### PR TITLE
Update react docs

### PR DESCRIPTION
**Pull request by johnthepink**
Change to `react-apollo`

### CODE REVIEW

**Comment by stubailo** [comment]
Thanks!

I'm a bit worried about duplicating between that readme and here, this stuff will probably happen often.

**Comment by johnthepink** [comment]
@stubailo should we just clear out that readme and add a link to the docs?

**Comment by stubailo** [comment]
Yeah that sounds like a good idea to me! That's what I've done for `apollo-client`.

**Comment by johnthepink** [comment]
on it

**Pull request merged**
