### PR TITLE
Fix argument for applyAfterware function call

### PR DESCRIPTION
**Pull request by mikeifomin**
Fix argument for applyAfterware function:
Corresponding https://github.com/apollostack/apollo-client/blob/v0.4.13/src/networkInterface.ts#L149

### CODE REVIEW

**Comment by helfer** [comment]
Thanks a lot! Can you do two more things, please?

1. fix this sentence: " [...] that a response **returns, and** options [...]"
2. make it clearer what the `options` object does and when you would use it, maybe by providing an example of what would go in there.

**Comment by mikeifomin** [comment]
@helfer 
Cant imagine any practical usage of `options` in this afterware implementation. 

Maybe if in the afterware function was possible to change `options` for already created `networkInterface`.
For example in case when graphQL server return 401, client has to update JWT from other API server. 

```js
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import {getNewToken} from './helpers';

const networkInterface = createNetworkInterface('/graphql',{
 extraField:"some value", // 
});

networkInterface.useAfter([{
  applyAfterware({response, options, /* updateOptions -  will be usefull*/}, next) {
    if (response.status === 401) {

      // this actually not usefull
      // options is a new object so we cant modify options of the networkInterface
      console.log(options.extraField)
      // 
      getNewToken();
    }
    next();
  }
}]);

const client = new ApolloClient({
  networkInterface,
});
```

And by the way.
Is it better to store JWT token inside the `networkInterface`? 
Not using middlewares for modify `req.headers` each time. So `networkInterface` can be main storage of JWT while javascript runtime.

**Comment by helfer** [comment]
If the options aren't useful, do we need to document them at all? Should we just stick to `{ response }`

**Comment by mikeifomin** [comment]
I think developer must know about extra params passed to function, even we can't write now usable example.

So there are 2 options:

 - `{response, options}` 

    pros:
      + transparent from source code
      + someone can use for its own purposes

    cons:
      -  if in next version this options will deprecated, then future api was not compatible 

 - `{response}` 

   pros:
     + clean and simple
     + in future this params can add more keys like updateOptions callback. no break current api
     + compact docs

   cons:
     - **developer can forget curve braces**.  
     - developer can ask a question why not simple `response`, without braces.

**Comment by helfer** [comment]
I'd prefer leaving it at `{ response }` if there's no useful example. I don't think people will forget the braces, because they are meaningful.

**Comment by mikeifomin** [comment]
Done. Please check.

**Comment by helfer** [comment]
Thanks!!

**Pull request merged**
