### PR TITLE
Redux Dev tools docs

### PR DESCRIPTION
**Pull request by abhiaiyer91**
For [#9](https://github.com/apollostack/docs/issues/9)
Took a stab at adding screenshots of the dev tools and explaining how state changes.

### CODE REVIEW

**Comment by abhiaiyer91** [comment]
@stubailo quick review?

**Comment by stubailo** [comment]
Looks great!

**Comment by stubailo** [comment]
I'd probably prefer to have fewer screenshots and maybe code snippets for the actions instead, so that they are easier to update if we change them!

**Comment by abhiaiyer91** [comment]
Lets do code snippets when we do Lifecycle of queries?

**Comment by stubailo** [comment]
Yeah sounds great!

**Pull request merged**
